import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
          {/* Middle rectangle */}
          <div className="text-6xl w-full p-10 rounded-lg shadow-inner absolute top-0 flex items-center justify-center text-white font-semibold tracking-wide" style={{backgroundColor: "#c33b3b"}}>
             HEATMAP MATCHUP
          </div>

        


        {children}
      </body>
      </AppRouterCacheProvider>
    </html>
  );
}
